[[recent]]
url = "file:///home/jake/Downloads/smashball.swf"
name = "smashball.swf"

[[recent]]
url = "http://m2.nflrush.com/a/game_swf/nation.swf"
name = "nation.swf"

[[recent]]
url = "http://www.avalanchegame.org/avalanchejump.swf"
name = "avalanchejump.swf"
